spring:
  application:
    name: auth
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/crypto-exchange
    username: crypto
    password: password
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/crypto-exchange
    user: crypto
    password: password

springdoc:
  api-docs:
    path: "/api-docs/v3/openapi"
    enabled: true
  swagger-ui:
    path: "/api-docs/swagger-ui"
    disable-swagger-default-url: true
    use-root-path: true
    syntax-highlight:
      theme: "arta"
    enabled: true